# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180417_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='User',
        ),
    ]
